package com.dynamo2.myerp.crm.dao.entities;

// Generated Mar 28, 2012 10:41:28 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * CustomerAccountRelationship generated by hbm2java
 */
@Entity
@Table(name = "customer_account_relationship")
@NamedQueries(value = {
		@NamedQuery(name = "listAccountsBoundWithCustomer", query = "select car.boundAccount from CustomerAccountRelationship car where car.customerId=?"),
		@NamedQuery(name = "deleteByCustomerIdAndAccount", query = "delete CustomerAccountRelationship car where car.customerId=? and car.boundAccount=?"),
		@NamedQuery(name = "listCustomersToMe", query = "select c from CustomerAccountRelationship car left join car.customer c where car.boundAccount=?") })
public class CustomerAccountRelationship implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Long customerId;
	private String boundAccount;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;
	private Customer customer;
	private Account account;

	public CustomerAccountRelationship() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "bound_account")
	public String getBoundAccount() {
		return boundAccount;
	}

	public void setBoundAccount(String boundAccount) {
		this.boundAccount = boundAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@OneToOne
	@JoinColumn(name = "customer_id", insertable = false, updatable = false)
	@Fetch(FetchMode.JOIN)
	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@OneToOne
	@JoinColumn(name = "bound_account", referencedColumnName = "account", insertable = false, updatable = false)
	@Fetch(FetchMode.JOIN)
	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
