package com.dynamo2.myerp.crm.dao.entities;

// Generated Aug 2, 2012 2:57:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerRelationshipsGraph generated by hbm2java
 */
@Entity
@Table(name = "customer_relationships_graph")
@NamedQueries(value = {
		@NamedQuery(name = "findRightByLeft", query = "from CustomerRelationshipsGraph c where c.leftCustomerId=? and c.type=?"),
		@NamedQuery(name = "findLeftByRight", query = "from CustomerRelationshipsGraph c where c.rightCustomerId=? and c.type=?") })
public class CustomerRelationshipsGraph implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Long leftCustomerId;
	private Long rightCustomerId;
	private String type;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;

	public CustomerRelationshipsGraph() {
	}

	public CustomerRelationshipsGraph(Long leftCustomerId, Long rightCustomerId, String type, Date lastModified) {
		this.leftCustomerId = leftCustomerId;
		this.rightCustomerId = rightCustomerId;
		this.type = type;
		this.lastModified = lastModified;
	}

	public CustomerRelationshipsGraph(Long leftCustomerId, Long rightCustomerId, String type, Date created,
			String createdBy, Date lastModified, String lastModifiedBy) {
		this.leftCustomerId = leftCustomerId;
		this.rightCustomerId = rightCustomerId;
		this.type = type;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "left_customer_id", nullable = false)
	public Long getLeftCustomerId() {
		return this.leftCustomerId;
	}

	public void setLeftCustomerId(Long leftCustomerId) {
		this.leftCustomerId = leftCustomerId;
	}

	@Column(name = "right_customer_id", nullable = false)
	public Long getRightCustomerId() {
		return this.rightCustomerId;
	}

	public void setRightCustomerId(Long rightCustomerId) {
		this.rightCustomerId = rightCustomerId;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

}
