package com.dynamo2.myerp.crm.dao.entities;

// Generated Mar 24, 2012 8:55:50 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer")
@NamedQueries(value = { @NamedQuery(name = "findCustomerByName", query = "from Customer cus where cus.name=?"),
		@NamedQuery(name = "findCustomerByCustomerId", query = "from Customer cus where cus.customerId=?"),
		@NamedQuery(name = "getMaxCustomerSeqNumer", query = "select max(cus.customerSeqNum) from Customer cus"),
		@NamedQuery(name = "listDistributors", query = "from Customer cus where cus.isDistributor = 1") })
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private String name;
	private String customerId;
	private Long customerSeqNum;
	private String salesAccount;
	private String outsideSalesAccount;
	private String agentAccount;
	private String customerServiceAccount;
	private String address1;
	private String address2;
	private String address3;
	private String fax1;
	private String fax2;
	private String fax3;
	private String website;
	private String quality;
	private String industry;
	private String type;
	private String annualAvenue;
	private String area;
	private String province;
	private String city;
	private String phone;
	private String phone2;
	private String phone3;
	private String email;
	private String hearFrom;
	private String notes;
	private boolean isDistributor;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;
	private Long serviceStatus;

	public Customer() {
	}

	public Customer(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 45, unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sales_account", nullable = false)
	public String getSalesAccount() {
		return this.salesAccount;
	}

	public void setSalesAccount(String salesAccount) {
		this.salesAccount = salesAccount;
	}

	@Column(name = "address1", length = 45)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 45)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address3", length = 45)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "fax1", length = 45)
	public String getFax1() {
		return this.fax1;
	}

	public void setFax1(String fax1) {
		this.fax1 = fax1;
	}

	@Column(name = "fax2", length = 45)
	public String getFax2() {
		return this.fax2;
	}

	public void setFax2(String fax2) {
		this.fax2 = fax2;
	}

	@Column(name = "fax3", length = 45)
	public String getFax3() {
		return this.fax3;
	}

	public void setFax3(String fax3) {
		this.fax3 = fax3;
	}

	@Column(name = "website", length = 45)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "quality", length = 45)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "industry", length = 45)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "annual_avenue", length = 45)
	public String getAnnualAvenue() {
		return this.annualAvenue;
	}

	public void setAnnualAvenue(String annualAvenue) {
		this.annualAvenue = annualAvenue;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "hear_from", length = 45)
	public String getHearFrom() {
		return this.hearFrom;
	}

	public void setHearFrom(String hearFrom) {
		this.hearFrom = hearFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "outside_sales_account")
	public String getOutsideSalesAccount() {
		return outsideSalesAccount;
	}

	public void setOutsideSalesAccount(String outsideSalesAccount) {
		this.outsideSalesAccount = outsideSalesAccount;
	}

	@Column(name = "agent_account")
	public String getAgentAccount() {
		return agentAccount;
	}

	public void setAgentAccount(String agentAccount) {
		this.agentAccount = agentAccount;
	}

	@Column(name = "customer_service_account")
	public String getCustomerServiceAccount() {
		return customerServiceAccount;
	}

	public void setCustomerServiceAccount(String customerServiceAccount) {
		this.customerServiceAccount = customerServiceAccount;
	}

	@Column(name = "province")
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "notes")
	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "area")
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "customer_id")
	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_seq_num")
	public Long getCustomerSeqNum() {
		return customerSeqNum;
	}

	public void setCustomerSeqNum(Long customerSeqNum) {
		this.customerSeqNum = customerSeqNum;
	}

	@Column(name = "phone2")
	public String getPhone2() {
		return phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "phone3")
	public String getPhone3() {
		return phone3;
	}

	public void setPhone3(String phone3) {
		this.phone3 = phone3;
	}

	@Column(name = "is_distributor")
	public boolean getIsDistributor() {
		return isDistributor;
	}

	public void setIsDistributor(boolean isDistributor) {
		this.isDistributor = isDistributor;
	}
	
	@Column(name = "service_status")
	public Long getServiceStatus() {
		return serviceStatus;
	}

	public void setServiceStatus(Long serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	@Override
	public String toString() {
		return "Customer [id=" + id + ", name=" + name + ", salesAccount=" + salesAccount + ", outsideSalesAccount="
				+ outsideSalesAccount + ", agentAccount=" + agentAccount + ", customerServiceAccount="
				+ customerServiceAccount + ", address1=" + address1 + ", address2=" + address2 + ", address3="
				+ address3 + ", fax1=" + fax1 + ", fax2=" + fax2 + ", fax3=" + fax3 + ", website=" + website
				+ ", quality=" + quality + ", industry=" + industry + ", type=" + type + ", annualAvenue="
				+ annualAvenue + ", province=" + province + ", city=" + city + ", phone=" + phone + ", email=" + email
				+ ", hearFrom=" + hearFrom + ", notes=" + notes + ", created=" + created + ", createdBy=" + createdBy
				+ ", lastModified=" + lastModified + ", lastModifiedBy=" + lastModifiedBy + "]";
	}

}
