package com.dynamo2.myerp.crm.dao.entities;

// Generated Jan 13, 2013 5:23:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnumList generated by hbm2java
 */
@Entity
@Table(name = "enum_list", catalog = "mycrm")
public class EnumList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String type;
	private String language;
	private String value;
	private Integer showPosition;
	private Date created;
	private String lastModifiedBy;
	private String createdBy;
	private Date lastModified;

	public EnumList() {
	}

	public EnumList(String type, Date lastModified) {
		this.type = type;
		this.lastModified = lastModified;
	}

	public EnumList(String type, String language, String value, Date created, String lastModifiedBy, String createdBy,
			Date lastModified) {
		this.type = type;
		this.language = language;
		this.value = value;
		this.created = created;
		this.lastModifiedBy = lastModifiedBy;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "language", length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "show_position")
	public Integer getShowPosition() {
		return showPosition;
	}

	public void setShowPosition(Integer showPosition) {
		this.showPosition = showPosition;
	}

}
