package com.dynamo2.myerp.crm.dao.entities;

// Generated Dec 20, 2012 8:48:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HelpContent generated by hbm2java
 */
@Entity
@Table(name = "help_content")
public class HelpContent implements java.io.Serializable {

	private Long id;
	private String title;
	private String pageFilePath;
	private String type;
	private String content;
	private String language;
	private Date created;
	private String lastModifiedBy;
	private String createdBy;
	private Date lastModified;

	public HelpContent() {
	}

	public HelpContent(String title, String pageFilePath, String type, String content, String language,
			Date lastModified) {
		this.title = title;
		this.pageFilePath = pageFilePath;
		this.type = type;
		this.content = content;
		this.language = language;
		this.lastModified = lastModified;
	}

	public HelpContent(String title, String pageFilePath, String type, String content, String language, Date created,
			String lastModifiedBy, String createdBy, Date lastModified) {
		this.title = title;
		this.pageFilePath = pageFilePath;
		this.type = type;
		this.content = content;
		this.language = language;
		this.created = created;
		this.lastModifiedBy = lastModifiedBy;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "page_file_path", nullable = false)
	public String getPageFilePath() {
		return this.pageFilePath;
	}

	public void setPageFilePath(String pageFilePath) {
		this.pageFilePath = pageFilePath;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "language", nullable = false, length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
