package com.dynamo2.myerp.crm.dao.entities;

// Generated Mar 24, 2012 8:55:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes")
public class Notes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FOR_TODO = "todo";
	public final static String FOR_CUSTOMER = "customer";

	private Long id;
	private Long forId;
	private String forType;
	private String notes;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;
	private String forRoleName;

	public Notes() {
	}

	public Notes(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Notes(Long forId, String forType, String notes, Date created, String createdBy, Date lastModified,
			String lastModifiedBy) {
		this.forId = forId;
		this.forType = forType;
		this.notes = notes;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "for_id")
	public Long getForId() {
		return this.forId;
	}

	public void setForId(Long forId) {
		this.forId = forId;
	}

	@Column(name = "for_type")
	public String getForType() {
		return this.forType;
	}

	public void setForType(String forType) {
		this.forType = forType;
	}
	
	@Column(name = "for_role_name")
	public String getForRoleName() {
		return this.forRoleName;
	}

	public void setForRoleName(String forRoleName) {
		this.forRoleName = forRoleName;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

}
