package com.dynamo2.myerp.crm.dao.entities;

// Generated Dec 8, 2012 9:39:03 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

import com.dynamo2.myerp.service.PERMISSION_DEFINITION_ENUM;

/**
 * RoleToPermissions generated by hbm2java
 */
@Entity
@Table(name = "ROLE_TO_PERMISSIONS")
public class RoleToPermissions implements java.io.Serializable {

	private static final long serialVersionUID = -5830995567641735288L;
	private Long id;
	private String roleName;
	private String permissions;
	private Date created;
	private String lastModifiedBy;
	private String createdBy;
	private Date lastModified;

	public RoleToPermissions() {
	}

	public RoleToPermissions(String roleName, String permissions, Date lastModified) {
		this.roleName = roleName;
		this.permissions = permissions;
		this.lastModified = lastModified;
	}

	public RoleToPermissions(String roleName, String permissions, Date created, String lastModifiedBy,
			String createdBy, Date lastModified) {
		this.roleName = roleName;
		this.permissions = permissions;
		this.created = created;
		this.lastModifiedBy = lastModifiedBy;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "PERMISSIONS", nullable = false, length = 65535)
	public String getPermissions() {
		return this.permissions;
	}
	
	@Transient
	public List<String> getPermissionList() {
		if (StringUtils.isBlank(this.permissions)) {
			return new LinkedList<String>();
		}

		String[] l = permissions.split(",");
		LinkedList<String> ps = new LinkedList<String>();
		for (String p : l) {
			ps.add(p);
		}

		return ps;
	}

	public void setPermissions(String permissions) {
		this.permissions = permissions;
	}

	public void setPermissionList(List<String> ps) {
		StringBuilder sb = new StringBuilder();
		for (String p : ps) {
			sb.append(p).append(',');
		}

		if (sb.charAt(sb.length() - 1) == ',') {
			sb.deleteCharAt(sb.length() - 1);
		}

		setPermissions(sb.toString());
	}

	public void setPermissions(List<PERMISSION_DEFINITION_ENUM> ps) {
		StringBuilder sb = new StringBuilder();
		for (PERMISSION_DEFINITION_ENUM p : ps) {
			sb.append(p.name()).append(',');
		}

		if (sb.charAt(sb.length() - 1) == ',') {
			sb.deleteCharAt(sb.length() - 1);
		}

		setPermissions(sb.toString());

	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}
}
