package com.dynamo2.myerp.dynamicform.dao.entities;

// Generated May 20, 2012 10:01:52 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.dynamo2.myerp.dynamicform.dao.entities.resultmap.FormListEntry;

/**
 * DynamicFormDefault generated by hbm2java
 */
@Entity
@Table(name = "dynamic_form_default")
@SqlResultSetMapping(name = "FormListEntryMapping", entities = @EntityResult(entityClass = FormListEntry.class))
@NamedNativeQueries(value = {
		@NamedNativeQuery(name = "listFormsToMe", query = "select d.customer_id customerId, d.summary, d.form_biz_id formBizId, d.id, d.status, d.created_by createdBy, d.created, d.last_modified lastModified, d.last_modified_by lastModifiedBy, d.assignee_account assigneeAccount, f.form_label formLabel"
				+ " from dynamic_form_default d left join form_metadata f on (d.form_metadata_id=f.id) "
				+ " where (d.created_by = ? or d.last_modified_by = ? or d.assignee_account = ?) and (d.form_metadata_id = ?) and (d.status <> 'DELETED')"
				+ " order by d.last_modified desc", resultSetMapping = "FormListEntryMapping"),
        @NamedNativeQuery(name = "listBelongedFormsToMe", query = "select d.customer_id customerId, d.summary, d.form_biz_id formBizId, d.id, d.status, d.created_by createdBy, d.created, d.last_modified lastModified, d.last_modified_by lastModifiedBy, d.assignee_account assigneeAccount, f.form_label formLabel"
                + " from dynamic_form_default d left join form_metadata f on (d.form_metadata_id=f.id) "
                + " where (d.created_by in (:createBy) or d.last_modified_by in (:modifiedBy) or d.assignee_account in (:assigneeAccount)) and (d.form_metadata_id = :formId) and (d.status <> 'DELETED')"
                + " order by d.last_modified desc", resultSetMapping = "FormListEntryMapping"),
        @NamedNativeQuery(name = "listFormsToParentForm", query = "select d.customer_id customerId, d.summary, d.form_biz_id formBizId, d.id, d.status, d.created_by createdBy, d.created, d.last_modified lastModified, d.last_modified_by lastModifiedBy, d.assignee_account assigneeAccount, f.form_label formLabel"
                + " from dynamic_form_default d left join form_metadata f on (d.form_metadata_id=f.id) "
                + " where (d.parent_form_biz_id = ?) and (d.form_metadata_id = ?) and (d.status <> 'DELETED')"
                + " order by d.last_modified desc limit 5", resultSetMapping = "FormListEntryMapping"),
		@NamedNativeQuery(name = "listAllForms", query = "select d.customer_id customerId, d.summary, d.form_biz_id formBizId, d.id, d.status, d.created_by createdBy, d.created, d.last_modified lastModified, d.last_modified_by lastModifiedBy, d.assignee_account assigneeAccount, f.form_label formLabel"
				+ " from dynamic_form_default d left join form_metadata f on (d.form_metadata_id=f.id) "
				+ " where d.form_metadata_id = ? and d.status <> 'DELETED'" + " order by d.last_modified desc", resultSetMapping = "FormListEntryMapping"),
		@NamedNativeQuery(name = "listAllFormsForCustomer", query = "select d.customer_id customerId, d.summary, d.form_biz_id formBizId, d.id, d.status, d.created_by createdBy, d.created, d.last_modified lastModified, d.last_modified_by lastModifiedBy, d.assignee_account assigneeAccount, f.form_label formLabel"
				+ " from dynamic_form_default d left join form_metadata f on (d.form_metadata_id=f.id) "
				+ " where d.customer_id = ? and d.form_metadata_id = ? and d.status <> 'DELETED'"
				+ " order by d.last_modified desc", resultSetMapping = "FormListEntryMapping"),
		@NamedNativeQuery(name = "listFormsOperatedByMe", query = "select d.customer_id customerId, d.summary, d.form_biz_id formBizId, d.id, d.status, d.created_by createdBy, d.created, d.last_modified lastModified, d.last_modified_by lastModifiedBy, d.assignee_account assigneeAccount, f.form_label formLabel"
				+ " from dynamic_form_default d left join form_metadata f on (d.form_metadata_id=f.id) "
				+ " where d.status <> 'DELETED' and "
				+ " exists (select audit.id from dynamic_form_default_audit_log audit "
				+ "         where audit.account = ? and audit.form_id = d.id)" + " order by d.last_modified desc", resultSetMapping = "FormListEntryMapping") })
@NamedQueries(value = {
		@NamedQuery(name = "updateDynamicFormDefaultAssignTo", query = "update DynamicFormDefault d set d.assigneeAccount=? where id=?"),
		@NamedQuery(name = "updateDynamicFormDefaultStatus", query = "update DynamicFormDefault d set d.status=? where id=?"),
		@NamedQuery(name = "getFormIdByBizId", query = "select d.id from DynamicFormDefault d where d.formBizId=?") })
public class DynamicFormDefault implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Long formMetadataId;
	private String formName;
	private String formBizId;
	private String parentFormBizId;
	private Long customerId;
	private String summary;
	private byte[] attachment;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;
	private String assigneeAccount;
	private String status;
	private String customVarchar1;
	private String customVarchar2;
	private String customVarchar3;
	private String customVarchar4;
	private String customVarchar5;
	private String customVarchar6;
	private String customVarchar7;
	private String customVarchar8;
	private String customVarchar9;
	private String customVarchar10;
	private String customVarchar11;
	private String customVarchar12;
	private String customVarchar13;
	private String customVarchar14;
	private String customVarchar15;
	private String customVarchar16;
	private String customVarchar17;
	private String customVarchar18;
	private String customVarchar19;
	private String customVarchar20;
	private String customVarchar21;
	private String customVarchar22;
	private String customVarchar23;
	private String customVarchar24;
	private String customVarchar25;
	private String customVarchar26;
	private String customVarchar27;
	private String customVarchar28;
	private String customVarchar29;
	private String customVarchar30;
	private String customVarchar31;
	private String customVarchar32;
	private String customVarchar33;
	private String customVarchar34;
	private String customVarchar35;
	private String customVarchar36;
	private String customVarchar37;
	private String customVarchar38;
	private String customVarchar39;
	private String customVarchar40;
	private String customVarchar41;
	private String customVarchar42;
	private String customVarchar43;
	private String customVarchar44;
	private String customVarchar45;
	private String customVarchar46;
	private String customVarchar47;
	private String customVarchar48;
	private String customVarchar49;
	private String customVarchar50;
	private Integer customInt1;
	private Integer customInt2;
	private Integer customInt3;
	private Integer customInt4;
	private Integer customInt5;
	private Integer customInt6;
	private Integer customInt7;
	private Integer customInt8;
	private Integer customInt9;
	private Integer customInt10;
	private Double customDouble1;
	private Double customDouble2;
	private Double customDouble3;
	private Double customDouble4;
	private Double customDouble5;
	private Double customDouble6;
	private Double customDouble7;
	private Double customDouble8;
	private Double customDouble9;
	private Double customDouble10;
	private Date customDatetime1;
	private Date customDatetime2;
	private Date customDatetime3;
	private Date customDatetime4;
	private Date customDatetime5;
	private Date customDatetime6;
	private Date customDatetime7;
	private Date customDatetime8;
	private Date customDatetime9;
	private Date customDatetime10;
	private String customText1;

	public DynamicFormDefault() {
	}

	public DynamicFormDefault(Long formMetadataId, String formName, Date created, String createdBy, Date lastModified,
			String lastModifiedBy, String assigneeAccount, String status) {
		this.formMetadataId = formMetadataId;
		this.formName = formName;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
		this.assigneeAccount = assigneeAccount;
		this.status = status;
	}

	public DynamicFormDefault(Long formMetadataId, String formName, String formBizId, Long customerId, String summary,
			byte[] attachment, Date created, String createdBy, Date lastModified, String lastModifiedBy,
			String assigneeAccount, String status, String customVarchar1, String customVarchar2, String customVarchar3,
			String customVarchar4, String customVarchar5, String customVarchar6, String customVarchar7,
			String customVarchar8, String customVarchar9, String customVarchar10, String customVarchar11,
			String customVarchar12, String customVarchar13, String customVarchar14, String customVarchar15,
			String customVarchar16, String customVarchar17, String customVarchar18, String customVarchar19,
			String customVarchar20, String customVarchar21, String customVarchar22, String customVarchar23,
			String customVarchar24, String customVarchar25, String customVarchar26, String customVarchar27,
			String customVarchar28, String customVarchar29, String customVarchar30, String customVarchar31,
			String customVarchar32, String customVarchar33, String customVarchar34, String customVarchar35,
			String customVarchar36, String customVarchar37, String customVarchar38, String customVarchar39,
			String customVarchar40, String customVarchar41, String customVarchar42, String customVarchar43,
			String customVarchar44, String customVarchar45, String customVarchar46, String customVarchar47,
			String customVarchar48, String customVarchar49, String customVarchar50, Integer customInt1,
			Integer customInt2, Integer customInt3, Integer customInt4, Integer customInt5, Integer customInt6,
			Integer customInt7, Integer customInt8, Integer customInt9, Integer customInt10, Double customDouble1,
			Double customDouble2, Double customDouble3, Double customDouble4, Double customDouble5,
			Double customDouble6, Double customDouble7, Double customDouble8, Double customDouble9,
			Double customDouble10, Date customDatetime1, Date customDatetime2, Date customDatetime3,
			Date customDatetime4, Date customDatetime5, Date customDatetime6, Date customDatetime7,
			Date customDatetime8, Date customDatetime9, Date customDatetime10, String customText1) {
		this.formMetadataId = formMetadataId;
		this.formName = formName;
		this.formBizId = formBizId;
		this.customerId = customerId;
		this.summary = summary;
		this.attachment = attachment;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
		this.assigneeAccount = assigneeAccount;
		this.status = status;
		this.customVarchar1 = customVarchar1;
		this.customVarchar2 = customVarchar2;
		this.customVarchar3 = customVarchar3;
		this.customVarchar4 = customVarchar4;
		this.customVarchar5 = customVarchar5;
		this.customVarchar6 = customVarchar6;
		this.customVarchar7 = customVarchar7;
		this.customVarchar8 = customVarchar8;
		this.customVarchar9 = customVarchar9;
		this.customVarchar10 = customVarchar10;
		this.customVarchar11 = customVarchar11;
		this.customVarchar12 = customVarchar12;
		this.customVarchar13 = customVarchar13;
		this.customVarchar14 = customVarchar14;
		this.customVarchar15 = customVarchar15;
		this.customVarchar16 = customVarchar16;
		this.customVarchar17 = customVarchar17;
		this.customVarchar18 = customVarchar18;
		this.customVarchar19 = customVarchar19;
		this.customVarchar20 = customVarchar20;
		this.customVarchar21 = customVarchar21;
		this.customVarchar22 = customVarchar22;
		this.customVarchar23 = customVarchar23;
		this.customVarchar24 = customVarchar24;
		this.customVarchar25 = customVarchar25;
		this.customVarchar26 = customVarchar26;
		this.customVarchar27 = customVarchar27;
		this.customVarchar28 = customVarchar28;
		this.customVarchar29 = customVarchar29;
		this.customVarchar30 = customVarchar30;
		this.customVarchar31 = customVarchar31;
		this.customVarchar32 = customVarchar32;
		this.customVarchar33 = customVarchar33;
		this.customVarchar34 = customVarchar34;
		this.customVarchar35 = customVarchar35;
		this.customVarchar36 = customVarchar36;
		this.customVarchar37 = customVarchar37;
		this.customVarchar38 = customVarchar38;
		this.customVarchar39 = customVarchar39;
		this.customVarchar40 = customVarchar40;
		this.customVarchar41 = customVarchar41;
		this.customVarchar42 = customVarchar42;
		this.customVarchar43 = customVarchar43;
		this.customVarchar44 = customVarchar44;
		this.customVarchar45 = customVarchar45;
		this.customVarchar46 = customVarchar46;
		this.customVarchar47 = customVarchar47;
		this.customVarchar48 = customVarchar48;
		this.customVarchar49 = customVarchar49;
		this.customVarchar50 = customVarchar50;
		this.customInt1 = customInt1;
		this.customInt2 = customInt2;
		this.customInt3 = customInt3;
		this.customInt4 = customInt4;
		this.customInt5 = customInt5;
		this.customInt6 = customInt6;
		this.customInt7 = customInt7;
		this.customInt8 = customInt8;
		this.customInt9 = customInt9;
		this.customInt10 = customInt10;
		this.customDouble1 = customDouble1;
		this.customDouble2 = customDouble2;
		this.customDouble3 = customDouble3;
		this.customDouble4 = customDouble4;
		this.customDouble5 = customDouble5;
		this.customDouble6 = customDouble6;
		this.customDouble7 = customDouble7;
		this.customDouble8 = customDouble8;
		this.customDouble9 = customDouble9;
		this.customDouble10 = customDouble10;
		this.customDatetime1 = customDatetime1;
		this.customDatetime2 = customDatetime2;
		this.customDatetime3 = customDatetime3;
		this.customDatetime4 = customDatetime4;
		this.customDatetime5 = customDatetime5;
		this.customDatetime6 = customDatetime6;
		this.customDatetime7 = customDatetime7;
		this.customDatetime8 = customDatetime8;
		this.customDatetime9 = customDatetime9;
		this.customDatetime10 = customDatetime10;
		this.customText1 = customText1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "form_metadata_id", nullable = false)
	public Long getFormMetadataId() {
		return this.formMetadataId;
	}

	public void setFormMetadataId(Long formMetadataId) {
		this.formMetadataId = formMetadataId;
	}

	@Column(name = "form_name", nullable = false)
	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

	@Column(name = "form_biz_id", length = 100)
	public String getFormBizId() {
		return this.formBizId;
	}

	public void setFormBizId(String formBizId) {
		this.formBizId = formBizId;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "summary")
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "attachment")
	public byte[] getAttachment() {
		return this.attachment;
	}

	public void setAttachment(byte[] attachment) {
		this.attachment = attachment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", nullable = false, length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", nullable = false, length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Column(name = "assignee_account", nullable = false, length = 45)
	public String getAssigneeAccount() {
		return this.assigneeAccount;
	}

	public void setAssigneeAccount(String assigneeAccount) {
		this.assigneeAccount = assigneeAccount;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "custom_varchar_1")
	public String getCustomVarchar1() {
		return this.customVarchar1;
	}

	public void setCustomVarchar1(String customVarchar1) {
		this.customVarchar1 = customVarchar1;
	}

	@Column(name = "custom_varchar_2")
	public String getCustomVarchar2() {
		return this.customVarchar2;
	}

	public void setCustomVarchar2(String customVarchar2) {
		this.customVarchar2 = customVarchar2;
	}

	@Column(name = "custom_varchar_3")
	public String getCustomVarchar3() {
		return this.customVarchar3;
	}

	public void setCustomVarchar3(String customVarchar3) {
		this.customVarchar3 = customVarchar3;
	}

	@Column(name = "custom_varchar_4")
	public String getCustomVarchar4() {
		return this.customVarchar4;
	}

	public void setCustomVarchar4(String customVarchar4) {
		this.customVarchar4 = customVarchar4;
	}

	@Column(name = "custom_varchar_5")
	public String getCustomVarchar5() {
		return this.customVarchar5;
	}

	public void setCustomVarchar5(String customVarchar5) {
		this.customVarchar5 = customVarchar5;
	}

	@Column(name = "custom_varchar_6")
	public String getCustomVarchar6() {
		return this.customVarchar6;
	}

	public void setCustomVarchar6(String customVarchar6) {
		this.customVarchar6 = customVarchar6;
	}

	@Column(name = "custom_varchar_7")
	public String getCustomVarchar7() {
		return this.customVarchar7;
	}

	public void setCustomVarchar7(String customVarchar7) {
		this.customVarchar7 = customVarchar7;
	}

	@Column(name = "custom_varchar_8")
	public String getCustomVarchar8() {
		return this.customVarchar8;
	}

	public void setCustomVarchar8(String customVarchar8) {
		this.customVarchar8 = customVarchar8;
	}

	@Column(name = "custom_varchar_9")
	public String getCustomVarchar9() {
		return this.customVarchar9;
	}

	public void setCustomVarchar9(String customVarchar9) {
		this.customVarchar9 = customVarchar9;
	}

	@Column(name = "custom_varchar_10")
	public String getCustomVarchar10() {
		return this.customVarchar10;
	}

	public void setCustomVarchar10(String customVarchar10) {
		this.customVarchar10 = customVarchar10;
	}

	@Column(name = "custom_varchar_11")
	public String getCustomVarchar11() {
		return this.customVarchar11;
	}

	public void setCustomVarchar11(String customVarchar11) {
		this.customVarchar11 = customVarchar11;
	}

	@Column(name = "custom_varchar_12")
	public String getCustomVarchar12() {
		return this.customVarchar12;
	}

	public void setCustomVarchar12(String customVarchar12) {
		this.customVarchar12 = customVarchar12;
	}

	@Column(name = "custom_varchar_13")
	public String getCustomVarchar13() {
		return this.customVarchar13;
	}

	public void setCustomVarchar13(String customVarchar13) {
		this.customVarchar13 = customVarchar13;
	}

	@Column(name = "custom_varchar_14")
	public String getCustomVarchar14() {
		return this.customVarchar14;
	}

	public void setCustomVarchar14(String customVarchar14) {
		this.customVarchar14 = customVarchar14;
	}

	@Column(name = "custom_varchar_15")
	public String getCustomVarchar15() {
		return this.customVarchar15;
	}

	public void setCustomVarchar15(String customVarchar15) {
		this.customVarchar15 = customVarchar15;
	}

	@Column(name = "custom_varchar_16")
	public String getCustomVarchar16() {
		return this.customVarchar16;
	}

	public void setCustomVarchar16(String customVarchar16) {
		this.customVarchar16 = customVarchar16;
	}

	@Column(name = "custom_varchar_17")
	public String getCustomVarchar17() {
		return this.customVarchar17;
	}

	public void setCustomVarchar17(String customVarchar17) {
		this.customVarchar17 = customVarchar17;
	}

	@Column(name = "custom_varchar_18")
	public String getCustomVarchar18() {
		return this.customVarchar18;
	}

	public void setCustomVarchar18(String customVarchar18) {
		this.customVarchar18 = customVarchar18;
	}

	@Column(name = "custom_varchar_19")
	public String getCustomVarchar19() {
		return this.customVarchar19;
	}

	public void setCustomVarchar19(String customVarchar19) {
		this.customVarchar19 = customVarchar19;
	}

	@Column(name = "custom_varchar_20")
	public String getCustomVarchar20() {
		return this.customVarchar20;
	}

	public void setCustomVarchar20(String customVarchar20) {
		this.customVarchar20 = customVarchar20;
	}

	@Column(name = "custom_varchar_21")
	public String getCustomVarchar21() {
		return this.customVarchar21;
	}

	public void setCustomVarchar21(String customVarchar21) {
		this.customVarchar21 = customVarchar21;
	}

	@Column(name = "custom_varchar_22")
	public String getCustomVarchar22() {
		return this.customVarchar22;
	}

	public void setCustomVarchar22(String customVarchar22) {
		this.customVarchar22 = customVarchar22;
	}

	@Column(name = "custom_varchar_23")
	public String getCustomVarchar23() {
		return this.customVarchar23;
	}

	public void setCustomVarchar23(String customVarchar23) {
		this.customVarchar23 = customVarchar23;
	}

	@Column(name = "custom_varchar_24")
	public String getCustomVarchar24() {
		return this.customVarchar24;
	}

	public void setCustomVarchar24(String customVarchar24) {
		this.customVarchar24 = customVarchar24;
	}

	@Column(name = "custom_varchar_25")
	public String getCustomVarchar25() {
		return this.customVarchar25;
	}

	public void setCustomVarchar25(String customVarchar25) {
		this.customVarchar25 = customVarchar25;
	}

	@Column(name = "custom_varchar_26")
	public String getCustomVarchar26() {
		return this.customVarchar26;
	}

	public void setCustomVarchar26(String customVarchar26) {
		this.customVarchar26 = customVarchar26;
	}

	@Column(name = "custom_varchar_27")
	public String getCustomVarchar27() {
		return this.customVarchar27;
	}

	public void setCustomVarchar27(String customVarchar27) {
		this.customVarchar27 = customVarchar27;
	}

	@Column(name = "custom_varchar_28")
	public String getCustomVarchar28() {
		return this.customVarchar28;
	}

	public void setCustomVarchar28(String customVarchar28) {
		this.customVarchar28 = customVarchar28;
	}

	@Column(name = "custom_varchar_29")
	public String getCustomVarchar29() {
		return this.customVarchar29;
	}

	public void setCustomVarchar29(String customVarchar29) {
		this.customVarchar29 = customVarchar29;
	}

	@Column(name = "custom_varchar_30")
	public String getCustomVarchar30() {
		return this.customVarchar30;
	}

	public void setCustomVarchar30(String customVarchar30) {
		this.customVarchar30 = customVarchar30;
	}

	@Column(name = "custom_varchar_31")
	public String getCustomVarchar31() {
		return this.customVarchar31;
	}

	public void setCustomVarchar31(String customVarchar31) {
		this.customVarchar31 = customVarchar31;
	}

	@Column(name = "custom_varchar_32")
	public String getCustomVarchar32() {
		return this.customVarchar32;
	}

	public void setCustomVarchar32(String customVarchar32) {
		this.customVarchar32 = customVarchar32;
	}

	@Column(name = "custom_varchar_33")
	public String getCustomVarchar33() {
		return this.customVarchar33;
	}

	public void setCustomVarchar33(String customVarchar33) {
		this.customVarchar33 = customVarchar33;
	}

	@Column(name = "custom_varchar_34")
	public String getCustomVarchar34() {
		return this.customVarchar34;
	}

	public void setCustomVarchar34(String customVarchar34) {
		this.customVarchar34 = customVarchar34;
	}

	@Column(name = "custom_varchar_35")
	public String getCustomVarchar35() {
		return this.customVarchar35;
	}

	public void setCustomVarchar35(String customVarchar35) {
		this.customVarchar35 = customVarchar35;
	}

	@Column(name = "custom_varchar_36")
	public String getCustomVarchar36() {
		return this.customVarchar36;
	}

	public void setCustomVarchar36(String customVarchar36) {
		this.customVarchar36 = customVarchar36;
	}

	@Column(name = "custom_varchar_37")
	public String getCustomVarchar37() {
		return this.customVarchar37;
	}

	public void setCustomVarchar37(String customVarchar37) {
		this.customVarchar37 = customVarchar37;
	}

	@Column(name = "custom_varchar_38")
	public String getCustomVarchar38() {
		return this.customVarchar38;
	}

	public void setCustomVarchar38(String customVarchar38) {
		this.customVarchar38 = customVarchar38;
	}

	@Column(name = "custom_varchar_39")
	public String getCustomVarchar39() {
		return this.customVarchar39;
	}

	public void setCustomVarchar39(String customVarchar39) {
		this.customVarchar39 = customVarchar39;
	}

	@Column(name = "custom_varchar_40")
	public String getCustomVarchar40() {
		return this.customVarchar40;
	}

	public void setCustomVarchar40(String customVarchar40) {
		this.customVarchar40 = customVarchar40;
	}

	@Column(name = "custom_varchar_41")
	public String getCustomVarchar41() {
		return this.customVarchar41;
	}

	public void setCustomVarchar41(String customVarchar41) {
		this.customVarchar41 = customVarchar41;
	}

	@Column(name = "custom_varchar_42")
	public String getCustomVarchar42() {
		return this.customVarchar42;
	}

	public void setCustomVarchar42(String customVarchar42) {
		this.customVarchar42 = customVarchar42;
	}

	@Column(name = "custom_varchar_43")
	public String getCustomVarchar43() {
		return this.customVarchar43;
	}

	public void setCustomVarchar43(String customVarchar43) {
		this.customVarchar43 = customVarchar43;
	}

	@Column(name = "custom_varchar_44")
	public String getCustomVarchar44() {
		return this.customVarchar44;
	}

	public void setCustomVarchar44(String customVarchar44) {
		this.customVarchar44 = customVarchar44;
	}

	@Column(name = "custom_varchar_45")
	public String getCustomVarchar45() {
		return this.customVarchar45;
	}

	public void setCustomVarchar45(String customVarchar45) {
		this.customVarchar45 = customVarchar45;
	}

	@Column(name = "custom_varchar_46")
	public String getCustomVarchar46() {
		return this.customVarchar46;
	}

	public void setCustomVarchar46(String customVarchar46) {
		this.customVarchar46 = customVarchar46;
	}

	@Column(name = "custom_varchar_47")
	public String getCustomVarchar47() {
		return this.customVarchar47;
	}

	public void setCustomVarchar47(String customVarchar47) {
		this.customVarchar47 = customVarchar47;
	}

	@Column(name = "custom_varchar_48")
	public String getCustomVarchar48() {
		return this.customVarchar48;
	}

	public void setCustomVarchar48(String customVarchar48) {
		this.customVarchar48 = customVarchar48;
	}

	@Column(name = "custom_varchar_49")
	public String getCustomVarchar49() {
		return this.customVarchar49;
	}

	public void setCustomVarchar49(String customVarchar49) {
		this.customVarchar49 = customVarchar49;
	}

	@Column(name = "custom_varchar_50")
	public String getCustomVarchar50() {
		return this.customVarchar50;
	}

	public void setCustomVarchar50(String customVarchar50) {
		this.customVarchar50 = customVarchar50;
	}

	@Column(name = "custom_int_1")
	public Integer getCustomInt1() {
		return this.customInt1;
	}

	public void setCustomInt1(Integer customInt1) {
		this.customInt1 = customInt1;
	}

	@Column(name = "custom_int_2")
	public Integer getCustomInt2() {
		return this.customInt2;
	}

	public void setCustomInt2(Integer customInt2) {
		this.customInt2 = customInt2;
	}

	@Column(name = "custom_int_3")
	public Integer getCustomInt3() {
		return this.customInt3;
	}

	public void setCustomInt3(Integer customInt3) {
		this.customInt3 = customInt3;
	}

	@Column(name = "custom_int_4")
	public Integer getCustomInt4() {
		return this.customInt4;
	}

	public void setCustomInt4(Integer customInt4) {
		this.customInt4 = customInt4;
	}

	@Column(name = "custom_int_5")
	public Integer getCustomInt5() {
		return this.customInt5;
	}

	public void setCustomInt5(Integer customInt5) {
		this.customInt5 = customInt5;
	}

	@Column(name = "custom_int_6")
	public Integer getCustomInt6() {
		return this.customInt6;
	}

	public void setCustomInt6(Integer customInt6) {
		this.customInt6 = customInt6;
	}

	@Column(name = "custom_int_7")
	public Integer getCustomInt7() {
		return this.customInt7;
	}

	public void setCustomInt7(Integer customInt7) {
		this.customInt7 = customInt7;
	}

	@Column(name = "custom_int_8")
	public Integer getCustomInt8() {
		return this.customInt8;
	}

	public void setCustomInt8(Integer customInt8) {
		this.customInt8 = customInt8;
	}

	@Column(name = "custom_int_9")
	public Integer getCustomInt9() {
		return this.customInt9;
	}

	public void setCustomInt9(Integer customInt9) {
		this.customInt9 = customInt9;
	}

	@Column(name = "custom_int_10")
	public Integer getCustomInt10() {
		return this.customInt10;
	}

	public void setCustomInt10(Integer customInt10) {
		this.customInt10 = customInt10;
	}

	@Column(name = "custom_double_1", precision = 22, scale = 0)
	public Double getCustomDouble1() {
		return this.customDouble1;
	}

	public void setCustomDouble1(Double customDouble1) {
		this.customDouble1 = customDouble1;
	}

	@Column(name = "custom_double_2", precision = 22, scale = 0)
	public Double getCustomDouble2() {
		return this.customDouble2;
	}

	public void setCustomDouble2(Double customDouble2) {
		this.customDouble2 = customDouble2;
	}

	@Column(name = "custom_double_3", precision = 22, scale = 0)
	public Double getCustomDouble3() {
		return this.customDouble3;
	}

	public void setCustomDouble3(Double customDouble3) {
		this.customDouble3 = customDouble3;
	}

	@Column(name = "custom_double_4", precision = 22, scale = 0)
	public Double getCustomDouble4() {
		return this.customDouble4;
	}

	public void setCustomDouble4(Double customDouble4) {
		this.customDouble4 = customDouble4;
	}

	@Column(name = "custom_double_5", precision = 22, scale = 0)
	public Double getCustomDouble5() {
		return this.customDouble5;
	}

	public void setCustomDouble5(Double customDouble5) {
		this.customDouble5 = customDouble5;
	}

	@Column(name = "custom_double_6", precision = 22, scale = 0)
	public Double getCustomDouble6() {
		return this.customDouble6;
	}

	public void setCustomDouble6(Double customDouble6) {
		this.customDouble6 = customDouble6;
	}

	@Column(name = "custom_double_7", precision = 22, scale = 0)
	public Double getCustomDouble7() {
		return this.customDouble7;
	}

	public void setCustomDouble7(Double customDouble7) {
		this.customDouble7 = customDouble7;
	}

	@Column(name = "custom_double_8", precision = 22, scale = 0)
	public Double getCustomDouble8() {
		return this.customDouble8;
	}

	public void setCustomDouble8(Double customDouble8) {
		this.customDouble8 = customDouble8;
	}

	@Column(name = "custom_double_9", precision = 22, scale = 0)
	public Double getCustomDouble9() {
		return this.customDouble9;
	}

	public void setCustomDouble9(Double customDouble9) {
		this.customDouble9 = customDouble9;
	}

	@Column(name = "custom_double_10", precision = 22, scale = 0)
	public Double getCustomDouble10() {
		return this.customDouble10;
	}

	public void setCustomDouble10(Double customDouble10) {
		this.customDouble10 = customDouble10;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_1", length = 19)
	public Date getCustomDatetime1() {
		return this.customDatetime1;
	}

	public void setCustomDatetime1(Date customDatetime1) {
		this.customDatetime1 = customDatetime1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_2", length = 19)
	public Date getCustomDatetime2() {
		return this.customDatetime2;
	}

	public void setCustomDatetime2(Date customDatetime2) {
		this.customDatetime2 = customDatetime2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_3", length = 19)
	public Date getCustomDatetime3() {
		return this.customDatetime3;
	}

	public void setCustomDatetime3(Date customDatetime3) {
		this.customDatetime3 = customDatetime3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_4", length = 19)
	public Date getCustomDatetime4() {
		return this.customDatetime4;
	}

	public void setCustomDatetime4(Date customDatetime4) {
		this.customDatetime4 = customDatetime4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_5", length = 19)
	public Date getCustomDatetime5() {
		return this.customDatetime5;
	}

	public void setCustomDatetime5(Date customDatetime5) {
		this.customDatetime5 = customDatetime5;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_6", length = 19)
	public Date getCustomDatetime6() {
		return this.customDatetime6;
	}

	public void setCustomDatetime6(Date customDatetime6) {
		this.customDatetime6 = customDatetime6;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_7", length = 19)
	public Date getCustomDatetime7() {
		return this.customDatetime7;
	}

	public void setCustomDatetime7(Date customDatetime7) {
		this.customDatetime7 = customDatetime7;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_8", length = 19)
	public Date getCustomDatetime8() {
		return this.customDatetime8;
	}

	public void setCustomDatetime8(Date customDatetime8) {
		this.customDatetime8 = customDatetime8;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_9", length = 19)
	public Date getCustomDatetime9() {
		return this.customDatetime9;
	}

	public void setCustomDatetime9(Date customDatetime9) {
		this.customDatetime9 = customDatetime9;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "custom_datetime_10", length = 19)
	public Date getCustomDatetime10() {
		return this.customDatetime10;
	}

	public void setCustomDatetime10(Date customDatetime10) {
		this.customDatetime10 = customDatetime10;
	}

	@Column(name = "custom_text_1", length = 65535)
	public String getCustomText1() {
		return this.customText1;
	}

	public void setCustomText1(String customText1) {
		this.customText1 = customText1;
	}

	@Column(name = "parent_form_biz_id")
	public String getParentFormBizId() {
		return parentFormBizId;
	}

	public void setParentFormBizId(String parentFormBizId) {
		this.parentFormBizId = parentFormBizId;
	}

}
