package com.dynamo2.myerp.dynamicform.dao.entities;

// Generated Jun 30, 2012 11:09:58 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DynamicFormDefaultAuditLog generated by hbm2java
 */
@Entity
@Table(name = "dynamic_form_default_audit_log")
@NamedQueries(value = {
		@NamedQuery(name = "listAuditLog", query = "from DynamicFormDefaultAuditLog d where d.formId=? order by d.created desc"),
		@NamedQuery(name = "listAuditLogByAccount", query = "from DynamicFormDefaultAuditLog d where d.account=? order by d.created desc") })
public class DynamicFormDefaultAuditLog implements java.io.Serializable {

	public enum LOG_OPERATIONS_ENUM {
		CREATE_NEW, MODIFY_DATA, MODIFY_ASSIGNEE, MODIFY_STATUS, DELETE_DATA
	};

	private static final long serialVersionUID = 6845908555436159926L;

	private Long id;
	private Long formId;
	private String account;
	private String plainLog;
	private String operation;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;

	public DynamicFormDefaultAuditLog() {
	}

	public DynamicFormDefaultAuditLog(Long id, Long formId, String account, String plainLog, Date lastModified) {
		this.id = id;
		this.formId = formId;
		this.account = account;
		this.plainLog = plainLog;
		this.lastModified = lastModified;
	}

	public DynamicFormDefaultAuditLog(Long id, Long formId, String account, String plainLog, String operation,
			Date created, String createdBy, Date lastModified, String lastModifiedBy) {
		this.id = id;
		this.formId = formId;
		this.account = account;
		this.plainLog = plainLog;
		this.operation = operation;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "form_id", nullable = false)
	public Long getFormId() {
		return this.formId;
	}

	public void setFormId(Long formId) {
		this.formId = formId;
	}

	@Column(name = "account", nullable = false, length = 45)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "plain_log", nullable = false, length = 65535)
	public String getPlainLog() {
		return this.plainLog;
	}

	public void setPlainLog(String plainLog) {
		this.plainLog = plainLog;
	}

	@Column(name = "operation", length = 255)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

}
