package com.dynamo2.myerp.dynamicform.dao.entities;

// Generated Nov 25, 2012 11:29:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailBox generated by hbm2java
 */
@Entity
@Table(name = "email_box", catalog = "mycrm")
public class EmailBox implements java.io.Serializable {

	public enum STATUS {WAITING, FAILED};	
	
	private Long id;
	private String messages;
	private String mailTo;
	private String status;
	private String errMsg;
	private String title;
	private String mailFrom;
	private Date created;
	private String createdBy;
	private Date lastModified;
	private String lastModifiedBy;

	public EmailBox() {
	}

	public EmailBox(String messages, String mailTo, String status, String title, String mailFrom, Date created,
			String createdBy, Date lastModified, String lastModifiedBy) {
		this.messages = messages;
		this.mailTo = mailTo;
		this.status = status;
		this.title = title;
		this.mailFrom = mailFrom;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
	}

	public EmailBox(String messages, String mailTo, String status, String errMsg, String title, String mailFrom,
			Date created, String createdBy, Date lastModified, String lastModifiedBy) {
		this.messages = messages;
		this.mailTo = mailTo;
		this.status = status;
		this.errMsg = errMsg;
		this.title = title;
		this.mailFrom = mailFrom;
		this.created = created;
		this.createdBy = createdBy;
		this.lastModified = lastModified;
		this.lastModifiedBy = lastModifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "messages", nullable = false, length = 65535)
	public String getMessages() {
		return this.messages;
	}

	public void setMessages(String messages) {
		this.messages = messages;
	}

	@Column(name = "mail_to", nullable = false)
	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "err_msg")
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "mail_from", nullable = false)
	public String getMailFrom() {
		return this.mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", nullable = false, length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "last_modified_by", nullable = false, length = 45)
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

}
