package com.dynamo2.myerp.dynamicform.dao.entities;

// Generated Jul 22, 2012 3:21:14 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.dynamo2.myerp.dynamicform.service.FormRecordStatus_ENUM;
import com.dynamo2.myerp.dynamicform.ui.controller.OrderMgmtBean;
import com.dynamo2.util.JSFUtils;

/**
 * FormWorkflow generated by hbm2java
 */
@Entity
@Table(name = "form_workflow", catalog = "mycrm", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "form_metadata_id", "step_name" }),
		@UniqueConstraint(columnNames = { "form_metadata_id", "step_sequence_number" }) })
@NamedQueries(value = { @NamedQuery(name = "listWorkFlowSteps", query = "from FormWorkflow where formMetadataId = ? order by stepSequenceNumber ASC") })
public class FormWorkflow implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Long formMetadataId;
	private String stepName;
	private String statusName;
	private String statusLabel;
	private int stepSequenceNumber;
	private String assigneeAccount;
	private String assigneeRole;
	private String approveToStepName;
	private String rejectToStepName;
	private String backToStepName;

	public FormWorkflow() {
	}

	public FormWorkflow(Long id, Long formMetadataId, String stepName, String statusName, String statusLabel,
			int stepSequenceNumber) {
		this.id = id;
		this.formMetadataId = formMetadataId;
		this.stepName = stepName;
		this.statusName = statusName;
		this.statusLabel = statusLabel;
		this.stepSequenceNumber = stepSequenceNumber;
	}

	public FormWorkflow(Long id, Long formMetadataId, String stepName, String statusName, String statusLabel,
			int stepSequenceNumber, String assigneeAccount, String assigneeRole, String approveToStepName,
			String rejectToStepName, String backToStepName) {
		this.id = id;
		this.formMetadataId = formMetadataId;
		this.stepName = stepName;
		this.statusName = statusName;
		this.statusLabel = statusLabel;
		this.stepSequenceNumber = stepSequenceNumber;
		this.assigneeAccount = assigneeAccount;
		this.assigneeRole = assigneeRole;
		this.approveToStepName = approveToStepName;
		this.rejectToStepName = rejectToStepName;
		this.backToStepName = backToStepName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "form_metadata_id", nullable = false)
	public Long getFormMetadataId() {
		return this.formMetadataId;
	}

	public void setFormMetadataId(Long formMetadataId) {
		this.formMetadataId = formMetadataId;
	}

	@Column(name = "step_name", nullable = false, length = 45)
	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	@Column(name = "status_name", nullable = false, length = 45)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "status_label", nullable = false, length = 45)
	public String getStatusLabel() {
		return this.statusLabel;
	}

	public void setStatusLabel(String statusLabel) {
		this.statusLabel = statusLabel;
	}

	@Column(name = "step_sequence_number", nullable = false)
	public int getStepSequenceNumber() {
		return this.stepSequenceNumber;
	}

	public void setStepSequenceNumber(int stepSequenceNumber) {
		this.stepSequenceNumber = stepSequenceNumber;
	}

	@Column(name = "assignee_account")
	public String getAssigneeAccount() {
		return this.assigneeAccount;
	}

	public void setAssigneeAccount(String assigneeAccount) {
		this.assigneeAccount = assigneeAccount;
	}

	@Column(name = "assignee_role")
	public String getAssigneeRole() {
		return this.assigneeRole;
	}

	public void setAssigneeRole(String assigneeRole) {
		this.assigneeRole = assigneeRole;
	}

	@Column(name = "approve_to_step_name", length = 45)
	public String getApproveToStepName() {
		return this.approveToStepName;
	}

	public void setApproveToStepName(String approveToStepName) {
		this.approveToStepName = approveToStepName;
	}

	@Column(name = "reject_to_step_name", length = 45)
	public String getRejectToStepName() {
		return this.rejectToStepName;
	}

	public void setRejectToStepName(String rejectToStepName) {
		this.rejectToStepName = rejectToStepName;
	}

	@Column(name = "back_to_step_name", length = 45)
	public String getBackToStepName() {
		return this.backToStepName;
	}

	public void setBackToStepName(String backToStepName) {
		this.backToStepName = backToStepName;
	}
	
//	public String getAsString(Object value) {
//		if (value == null || value.toString().isEmpty())
//			return "NA";
//
//		if (FormRecordStatus_ENUM.NEW.name().equalsIgnoreCase(value.toString())) {
//			return JSFUtils.getI18NMessage(FormRecordStatus_ENUM.NEW.name());
//		}
//
//		if (FormRecordStatus_ENUM.BACK_REFINE.name().equalsIgnoreCase(value.toString())) {
//			return JSFUtils.getI18NMessage(FormRecordStatus_ENUM.BACK_REFINE.name());
//		}
//
//		if (FormRecordStatus_ENUM.END.name().equalsIgnoreCase(value.toString())) {
//			return JSFUtils.getI18NMessage(FormRecordStatus_ENUM.END.name());
//		}
//
//		if (FormRecordStatus_ENUM.INVALID.name().equalsIgnoreCase(value.toString())) {
//			return JSFUtils.getI18NMessage(FormRecordStatus_ENUM.INVALID.name());
//		}
//
//		if (FormRecordStatus_ENUM.DELETED.name().equalsIgnoreCase(value.toString())) {
//			return JSFUtils.getI18NMessage(FormRecordStatus_ENUM.DELETED.name());
//		}
//
//		return this.getStatusLabel();	
//	}

}
