package com.dynamo2.myerp.crm.service.constant;

public enum TODO_TYPE_ENUM {
	TODO_CUSTOMER, TODO_PRODUCT, TODO_INDIVIDUAL_CASE, TODO_CONTRACT, TODO_SOLUTION, TODO_MARKETING_ACTIVITY, TODO_BUSINESS_OPPORTUNITY, TODO_ASSERT;
}
